version: '3.9' # Você pode até remover essa linha para evitar aviso, mas não é obrigatório

services:
    nextjs:
        build: .
        user: root
        container_name: portfolio
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
